export const MENU_ROUTE = '/menu'
export const BASKET_ROUTE = '/basket'
export const REGISTRATION_ROUTE = '/auth/registration'
export const LOGIN_ROUTE = '/auth/login'
export const DISH_ROUTE = '/dish'
export const PROFILE_ROUTE = '/profile'
export const ADMIN_ROUTE = '/admin'